# Generated by Django 3.1.1 on 2020-09-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(default='math'),
            preserve_default=False,
        ),
    ]
