# Generated by Django 3.1.1 on 2020-09-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0002_chapter_chapter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
