# Generated by Django 3.1.1 on 2020-09-24 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0004_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='standard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='standard.standard'),
        ),
    ]
