# Generated by Django 3.1.1 on 2020-09-24 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0005_notes_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='notes/'),
            preserve_default=False,
        ),
    ]
