# Generated by Django 3.1.1 on 2020-09-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0006_notes_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='file',
            field=models.FileField(upload_to='notes/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
