# Generated by Django 3.1.1 on 2020-09-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0007_auto_20200926_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='chapter',
            field=models.ManyToManyField(to='standard.Chapter'),
        ),
    ]
