# Generated by Django 3.1.1 on 2020-09-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0009_auto_20200926_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standard',
            name='subject',
        ),
    ]
