# Generated by Django 3.1.1 on 2020-09-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0009_auto_20200924_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='upload_file',
            field=models.FileField(upload_to='notes/%Y/%m/%d/'),
        ),
    ]
