# Generated by Django 3.1.1 on 2020-09-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0011_auto_20200926_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(),
        ),
    ]
