# Generated by Django 3.1.1 on 2020-09-26 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0012_auto_20200926_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='standard.subject'),
            preserve_default=False,
        ),
    ]
