# Generated by Django 3.1.1 on 2020-09-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0013_chapter_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter',
            new_name='chapter_name',
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_no',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='upload_file',
            field=models.FileField(default=1, upload_to='notes/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
