# Generated by Django 3.1.1 on 2020-09-26 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0016_book_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='subject',
            new_name='book',
        ),
    ]
