# Generated by Django 3.1.1 on 2020-09-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0017_auto_20200926_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
